"""Add reconciliation fields to bank_transactions

Revision ID: 0a534948f728
Revises: add_bank_account_model
Create Date: 2025-10-19 07:05:18.585898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a534948f728'
down_revision = 'add_bank_account_model'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reconciled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reconciled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reconciled_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bank_transactions_reconciled_by', 'users', ['reconciled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bank_transactions_reconciled_by', type_='foreignkey')
        batch_op.drop_column('reconciled_by_id')
        batch_op.drop_column('reconciled_at')
        batch_op.drop_column('is_reconciled')

    # ### end Alembic commands ###
