# Account constants for BigCapitalPy
# Based on the React version's comprehensive account structure

# Account Types
ACCOUNT_TYPE = {
    'CASH': 'cash',
    'BANK': 'bank',
    'ACCOUNTS_RECEIVABLE': 'accounts-receivable',
    'INVENTORY': 'inventory',
    'OTHER_CURRENT_ASSET': 'other-current-asset',
    'FIXED_ASSET': 'fixed-asset',
    'NON_CURRENT_ASSET': 'none-current-asset',
    'ACCOUNTS_PAYABLE': 'accounts-payable',
    'CREDIT_CARD': 'credit-card',
    'TAX_PAYABLE': 'tax-payable',
    'OTHER_CURRENT_LIABILITY': 'other-current-liability',
    'LONG_TERM_LIABILITY': 'long-term-liability',
    'NON_CURRENT_LIABILITY': 'non-current-liability',
    'EQUITY': 'equity',
    'INCOME': 'income',
    'OTHER_INCOME': 'other-income',
    'COST_OF_GOODS_SOLD': 'cost-of-goods-sold',
    'EXPENSE': 'expense',
    'OTHER_EXPENSE': 'other-expense',
}

# Account Parent Types
ACCOUNT_PARENT_TYPE = {
    'CURRENT_ASSET': 'current-asset',
    'FIXED_ASSET': 'fixed-asset',
    'NON_CURRENT_ASSET': 'non-current-asset',
    'CURRENT_LIABILITY': 'current-liability',
    'LONG_TERM_LIABILITY': 'long-term-liability',
    'NON_CURRENT_LIABILITY': 'non-current-liability',
    'EQUITY': 'equity',
    'EXPENSE': 'expense',
    'INCOME': 'income',
}

# Account Root Types
ACCOUNT_ROOT_TYPE = {
    'ASSET': 'asset',
    'LIABILITY': 'liability',
    'EQUITY': 'equity',
    'EXPENSE': 'expense',
    'INCOME': 'income',
}

# Account Normal Balance
ACCOUNT_NORMAL = {
    'CREDIT': 'credit',
    'DEBIT': 'debit',
}

# Account Types Configuration
ACCOUNT_TYPES = [
    {
        'label': 'Cash',
        'key': ACCOUNT_TYPE['CASH'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_ASSET'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'multi_currency': True,
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Bank',
        'key': ACCOUNT_TYPE['BANK'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_ASSET'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'multi_currency': True,
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Accounts Receivable',
        'key': ACCOUNT_TYPE['ACCOUNTS_RECEIVABLE'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_ASSET'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Inventory',
        'key': ACCOUNT_TYPE['INVENTORY'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_ASSET'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Other Current Asset',
        'key': ACCOUNT_TYPE['OTHER_CURRENT_ASSET'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_ASSET'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Fixed Asset',
        'key': ACCOUNT_TYPE['FIXED_ASSET'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'parent_type': ACCOUNT_PARENT_TYPE['FIXED_ASSET'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Non-Current Asset',
        'key': ACCOUNT_TYPE['NON_CURRENT_ASSET'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['ASSET'],
        'parent_type': ACCOUNT_PARENT_TYPE['FIXED_ASSET'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Accounts Payable',
        'key': ACCOUNT_TYPE['ACCOUNTS_PAYABLE'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_LIABILITY'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Credit Card',
        'key': ACCOUNT_TYPE['CREDIT_CARD'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_LIABILITY'],
        'multi_currency': True,
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Tax Payable',
        'key': ACCOUNT_TYPE['TAX_PAYABLE'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_LIABILITY'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Other Current Liability',
        'key': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['CURRENT_LIABILITY'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Long Term Liability',
        'key': ACCOUNT_TYPE['LONG_TERM_LIABILITY'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['LONG_TERM_LIABILITY'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Non-Current Liability',
        'key': ACCOUNT_TYPE['NON_CURRENT_LIABILITY'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['LIABILITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['NON_CURRENT_LIABILITY'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Equity',
        'key': ACCOUNT_TYPE['EQUITY'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['EQUITY'],
        'parent_type': ACCOUNT_PARENT_TYPE['EQUITY'],
        'balance_sheet': True,
        'income_sheet': False,
    },
    {
        'label': 'Income',
        'key': ACCOUNT_TYPE['INCOME'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['INCOME'],
        'parent_type': ACCOUNT_PARENT_TYPE['INCOME'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Other Income',
        'key': ACCOUNT_TYPE['OTHER_INCOME'],
        'normal': ACCOUNT_NORMAL['CREDIT'],
        'root_type': ACCOUNT_ROOT_TYPE['INCOME'],
        'parent_type': ACCOUNT_PARENT_TYPE['INCOME'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Cost of Goods Sold',
        'key': ACCOUNT_TYPE['COST_OF_GOODS_SOLD'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['EXPENSE'],
        'parent_type': ACCOUNT_PARENT_TYPE['EXPENSE'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Expense',
        'key': ACCOUNT_TYPE['EXPENSE'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['EXPENSE'],
        'parent_type': ACCOUNT_PARENT_TYPE['EXPENSE'],
        'balance_sheet': False,
        'income_sheet': True,
    },
    {
        'label': 'Other Expense',
        'key': ACCOUNT_TYPE['OTHER_EXPENSE'],
        'normal': ACCOUNT_NORMAL['DEBIT'],
        'root_type': ACCOUNT_ROOT_TYPE['EXPENSE'],
        'parent_type': ACCOUNT_PARENT_TYPE['EXPENSE'],
        'balance_sheet': False,
        'income_sheet': True,
    },
]

# Helper function to get account types that support multi-currency
def get_accounts_supports_multi_currency():
    return [account for account in ACCOUNT_TYPES if account.get('multi_currency', False)]

# Predefined Accounts (SeedAccounts from React version)
SEED_ACCOUNTS = [
    # Assets
    {
        'name': 'Bank Account',
        'slug': 'bank-account',
        'account_type': ACCOUNT_TYPE['BANK'],
        'code': '10001',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Saving Bank Account',
        'slug': 'saving-bank-account',
        'account_type': ACCOUNT_TYPE['BANK'],
        'code': '10002',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Undeposited Funds',
        'slug': 'undeposited-funds',
        'account_type': ACCOUNT_TYPE['CASH'],
        'code': '10003',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Petty Cash',
        'slug': 'petty-cash',
        'account_type': ACCOUNT_TYPE['CASH'],
        'code': '10004',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Computer Equipment',
        'slug': 'computer-equipment',
        'account_type': ACCOUNT_TYPE['FIXED_ASSET'],
        'code': '10005',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Office Equipment',
        'slug': 'office-equipment',
        'account_type': ACCOUNT_TYPE['FIXED_ASSET'],
        'code': '10006',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Accounts Receivable (A/R)',
        'slug': 'accounts-receivable',
        'account_type': ACCOUNT_TYPE['ACCOUNTS_RECEIVABLE'],
        'code': '10007',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Inventory Asset',
        'slug': 'inventory-asset',
        'account_type': ACCOUNT_TYPE['INVENTORY'],
        'code': '10008',
        'description': 'An account that holds valuation of products or goods that available for sale.',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    # Liabilities
    {
        'name': 'Accounts Payable (A/P)',
        'slug': 'accounts-payable',
        'account_type': ACCOUNT_TYPE['ACCOUNTS_PAYABLE'],
        'code': '20001',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Owner A Drawings',
        'slug': 'owner-drawings',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'code': '20002',
        'description': 'Withdrawals by the owners.',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Loan',
        'slug': 'loan',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'code': '20003',
        'description': 'Money that has been borrowed from a creditor.',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Opening Balance Liabilities',
        'slug': 'opening-balance-liabilities',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'code': '20004',
        'description': 'This account will hold the difference in the debits and credits entered during the opening balance.',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Revenue Received in Advance',
        'slug': 'revenue-received-in-advance',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'code': '20005',
        'description': 'When customers pay in advance for products/services.',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Tax Payable',
        'slug': 'tax-payable',
        'account_type': ACCOUNT_TYPE['TAX_PAYABLE'],
        'code': '20006',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    # Equity
    {
        'name': 'Retained Earnings',
        'slug': 'retained-earnings',
        'account_type': ACCOUNT_TYPE['EQUITY'],
        'code': '30001',
        'description': 'Retained earnings tracks net income from previous fiscal years.',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Opening Balance Equity',
        'slug': 'opening-balance-equity',
        'account_type': ACCOUNT_TYPE['EQUITY'],
        'code': '30002',
        'description': 'When you enter opening balances to the accounts, the amounts enter in Opening balance equity. This ensures that you have a correct trial balance sheet for your company, without even specific the second credit or debit entry.',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': "Owner's Equity",
        'slug': 'owner-equity',
        'account_type': ACCOUNT_TYPE['EQUITY'],
        'code': '30003',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Drawings',
        'slug': 'drawings',
        'account_type': ACCOUNT_TYPE['EQUITY'],
        'code': '30004',
        'description': 'Goods purchased with the intention of selling these to customers',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    # Expenses
    {
        'name': 'Other Expenses',
        'slug': 'other-expenses',
        'account_type': ACCOUNT_TYPE['OTHER_EXPENSE'],
        'code': '40001',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Cost of Goods Sold',
        'slug': 'cost-of-goods-sold',
        'account_type': ACCOUNT_TYPE['COST_OF_GOODS_SOLD'],
        'code': '40002',
        'description': 'Tracks the direct cost of the goods sold.',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Office expenses',
        'slug': 'office-expenses',
        'account_type': ACCOUNT_TYPE['EXPENSE'],
        'code': '40003',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    # Income
    {
        'name': 'Sales',
        'slug': 'sales',
        'account_type': ACCOUNT_TYPE['INCOME'],
        'code': '50001',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Service Revenue',
        'slug': 'service-revenue',
        'account_type': ACCOUNT_TYPE['INCOME'],
        'code': '50002',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Interest Income',
        'slug': 'interest-income',
        'account_type': ACCOUNT_TYPE['OTHER_INCOME'],
        'code': '50003',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': False,
    },
    {
        'name': 'Other Income',
        'slug': 'other-income',
        'account_type': ACCOUNT_TYPE['OTHER_INCOME'],
        'code': '50004',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Unearned Revenue',
        'slug': 'unearned-revenue',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_LIABILITY'],
        'code': '50005',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    # Other Assets/Liabilities
    {
        'name': 'Prepaid Expenses',
        'slug': 'prepaid-expenses',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_ASSET'],
        'code': '10009',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Stripe Clearing',
        'slug': 'stripe-clearing',
        'account_type': ACCOUNT_TYPE['OTHER_CURRENT_ASSET'],
        'code': '10010',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Discount',
        'slug': 'discount',
        'account_type': ACCOUNT_TYPE['OTHER_INCOME'],
        'code': '50006',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Purchase Discount',
        'slug': 'purchase-discount',
        'account_type': ACCOUNT_TYPE['OTHER_EXPENSE'],
        'code': '40004',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
    {
        'name': 'Other Charges',
        'slug': 'other-charges',
        'account_type': ACCOUNT_TYPE['OTHER_INCOME'],
        'code': '50007',
        'description': '',
        'active': True,
        'index': 1,
        'predefined': True,
    },
]